version: '3.8'

services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres-instance
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pguser
      POSTGRES_DB: pgdb
